In [12]:
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
import urllib.request, json
import os
import numpy as np
import tensorflow as tf # This code has been tested with TensorFlow 1.6
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.recurrent import LSTM
from keras.wrappers.scikit_learn import KerasClassifier
import time
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier  #GBM algorithm
from sklearn import cross_validation, metrics   #Additional scklearn functions
from sklearn.grid_search import GridSearchCV   #Perforing grid search

from sklearn.cross_validation import KFold

from sklearn.cross_validation import StratifiedKFold
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, BaggingClassifier
from collections import Counter
from sklearn.metrics import roc_auc_score, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

import xgboost as xgb #Gradient boosting

from xgboost import XGBClassifier
from sklearn.feature_selection import SelectFromModel #model selection
from sklearn.metrics import accuracy_score #model testing
import matplotlib.mlab as mlab  
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, log_loss
from sklearn import decomposition

from sklearn.preprocessing import LabelEncoder
from sklearn.cross_validation import StratifiedShuffleSplit

# LSTM for intraday price

In [13]:
data=pd.read_csv('/Users/dingding/Desktop/GIII_3minutenew.csv')
data=data.drop(data.index[[0,1,2,3]])
null_columns=data.columns[data.isnull().any()]
data[null_columns].isnull().sum()
data=data.dropna(subset = ['MFI_3', 'Donchian_3'])
features=data.iloc[:,2:-2]
labels=data.iloc[:,-1]
import pandas as pd
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(features)
features_normalized = pd.DataFrame(np_scaled)
X_train, X_test, y_train, y_test = train_test_split(features_normalized, labels, test_size=0.2, random_state=143)

# epochs: 10,50,100

In [71]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer='uniform'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=10, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))

[[3115  754]
 [ 830 3526]]
             precision    recall  f1-score   support

         -1       0.79      0.81      0.80      3869
          1       0.82      0.81      0.82      4356

avg / total       0.81      0.81      0.81      8225

0.8074164133738602


In [73]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer='uniform'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=50, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))

[[3123  746]
 [ 541 3815]]
             precision    recall  f1-score   support

         -1       0.85      0.81      0.83      3869
          1       0.84      0.88      0.86      4356

avg / total       0.84      0.84      0.84      8225

0.8435258358662614


In [74]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer='uniform'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))


[[3249  620]
 [ 601 3755]]
             precision    recall  f1-score   support

         -1       0.84      0.84      0.84      3869
          1       0.86      0.86      0.86      4356

avg / total       0.85      0.85      0.85      8225

0.8515501519756838


# Neuron Activation Function: linear softmax, sigmoid

In [76]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer='uniform', activation='linear'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))



[[3119  750]
 [ 489 3867]]
             precision    recall  f1-score   support

         -1       0.86      0.81      0.83      3869
          1       0.84      0.89      0.86      4356

avg / total       0.85      0.85      0.85      8225

0.8493617021276596


In [77]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer='uniform',activation='sigmoid'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))




[[3073  796]
 [ 634 3722]]
             precision    recall  f1-score   support

         -1       0.83      0.79      0.81      3869
          1       0.82      0.85      0.84      4356

avg / total       0.83      0.83      0.83      8225

0.8261398176291793


In [78]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer='uniform',activation='softmax'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))





[[2956  913]
 [ 570 3786]]
             precision    recall  f1-score   support

         -1       0.84      0.76      0.80      3869
          1       0.81      0.87      0.84      4356

avg / total       0.82      0.82      0.82      8225

0.8196960486322189


In [79]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer='uniform',activation='tanh'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))


[[2990  879]
 [ 343 4013]]
             precision    recall  f1-score   support

         -1       0.90      0.77      0.83      3869
          1       0.82      0.92      0.87      4356

avg / total       0.86      0.85      0.85      8225

0.8514285714285714


# Tune Dropout Regularization 0.0,0.1,.0.2,0.3

In [101]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer='uniform', activation='tanh', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.0))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
# summarize results
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))



[[3244  625]
 [ 581 3775]]
             precision    recall  f1-score   support

         -1       0.85      0.84      0.84      3869
          1       0.86      0.87      0.86      4356

avg / total       0.85      0.85      0.85      8225

0.8533738601823708


In [102]:
from keras.constraints import maxnorm
def create_model1():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer='uniform', activation='tanh', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.1))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model1= KerasClassifier(build_fn=create_model1, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model1.fit(X_train, y_train)
# summarize results
pre1=model.predict(X_test)
print(confusion_matrix(y_test, pre1))  
print(classification_report(y_test, pre1)) 
print (accuracy_score(y_test, pre1))

[[3244  625]
 [ 581 3775]]
             precision    recall  f1-score   support

         -1       0.85      0.84      0.84      3869
          1       0.86      0.87      0.86      4356

avg / total       0.85      0.85      0.85      8225

0.8533738601823708


In [104]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer='uniform', activation='tanh', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.2))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
# summarize results
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))

[[3424  445]
 [ 798 3558]]
             precision    recall  f1-score   support

         -1       0.81      0.88      0.85      3869
          1       0.89      0.82      0.85      4356

avg / total       0.85      0.85      0.85      8225

0.8488753799392097


In [83]:
from keras.constraints import maxnorm
def create_model(neurons=25):
	# create model
	model = Sequential()
	model.add(Dense(neurons, input_dim=X_train.shape[1], kernel_initializer='uniform', activation='linear', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.2))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
# summarize results
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))

[[3490  379]
 [ 887 3469]]
             precision    recall  f1-score   support

         -1       0.80      0.90      0.85      3869
          1       0.90      0.80      0.85      4356

avg / total       0.85      0.85      0.85      8225

0.8460790273556231


In [84]:
from keras.constraints import maxnorm
def create_model(neurons=30):
	# create model
	model = Sequential()
	model.add(Dense(neurons, input_dim=X_train.shape[1], kernel_initializer='uniform', activation='tanh', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.2))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_train, y_train)
# summarize results
pre=model.predict(X_test)
print(confusion_matrix(y_test, pre))  
print(classification_report(y_test, pre)) 
print (accuracy_score(y_test, pre))

[[3567  302]
 [1117 3239]]
             precision    recall  f1-score   support

         -1       0.76      0.92      0.83      3869
          1       0.91      0.74      0.82      4356

avg / total       0.84      0.83      0.83      8225

0.8274772036474164


# LSTM daily price

In [86]:
daily_data=pd.read_csv('/Users/dingding/Desktop/GIIIUS_daily_new.csv')
null_columns=daily_data.columns[daily_data.isnull().any()]
daily_data[null_columns].isnull().sum()
daily_data=daily_data.dropna(subset = ['Donchian_3'])
daily_data=daily_data.drop(['field','RETURN_COM_EQY','EBITDA','IS_EPS','PROF_MARGIN','ROC_3','Return_3','return/ebitda','return/EPS','return/pro','return/ROE'],axis = 1)

In [87]:
daily_features=daily_data.iloc[:,0:-1]
daily_labels=daily_data.iloc[:,-1]

In [88]:
min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(daily_features)
dailyfeatures_normalized = pd.DataFrame(np_scaled)

In [89]:
X_dailytrain, X_dailytest, y_dailytrain, y_dailytest = train_test_split(dailyfeatures_normalized, daily_labels, test_size = 0.20)  

# epochs: 10,50,100

In [90]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=10, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
print (accuracy_score(y_dailytest, pre_daily))

[[463 139]
 [180 536]]
             precision    recall  f1-score   support

         -1       0.72      0.77      0.74       602
          1       0.79      0.75      0.77       716

avg / total       0.76      0.76      0.76      1318

0.7579666160849773


In [91]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=50, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
print (accuracy_score(y_dailytest, pre_daily))

[[450 152]
 [171 545]]
             precision    recall  f1-score   support

         -1       0.72      0.75      0.74       602
          1       0.78      0.76      0.77       716

avg / total       0.76      0.75      0.76      1318

0.7549317147192717


In [92]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
print (accuracy_score(y_dailytest, pre_daily))

[[458 144]
 [175 541]]
             precision    recall  f1-score   support

         -1       0.72      0.76      0.74       602
          1       0.79      0.76      0.77       716

avg / total       0.76      0.76      0.76      1318

0.7579666160849773


# Neuron Activation Function: linear softmax, sigmoid

In [93]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform', activation='linear'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
print (accuracy_score(y_dailytest, pre_daily))


[[441 161]
 [167 549]]
             precision    recall  f1-score   support

         -1       0.73      0.73      0.73       602
          1       0.77      0.77      0.77       716

avg / total       0.75      0.75      0.75      1318

0.7511380880121397


In [94]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform', activation='sigmoid'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
print (accuracy_score(y_dailytest, pre_daily))

[[457 145]
 [176 540]]
             precision    recall  f1-score   support

         -1       0.72      0.76      0.74       602
          1       0.79      0.75      0.77       716

avg / total       0.76      0.76      0.76      1318

0.7564491654021245


In [95]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform', activation='softmax'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
print (accuracy_score(y_dailytest, pre_daily))

[[424 178]
 [151 565]]
             precision    recall  f1-score   support

         -1       0.74      0.70      0.72       602
          1       0.76      0.79      0.77       716

avg / total       0.75      0.75      0.75      1318

0.7503793626707133


# Tune Dropout Regularization 0.0,0.1,.0.2,0.3¶

In [96]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform', activation='sigmoid', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.0))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
print (accuracy_score(y_dailytest, pre_daily))



[[423 179]
 [152 564]]
             precision    recall  f1-score   support

         -1       0.74      0.70      0.72       602
          1       0.76      0.79      0.77       716

avg / total       0.75      0.75      0.75      1318

0.7488619119878603


In [97]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform', activation='sigmoid', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.1))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
print (accuracy_score(y_dailytest, pre_daily))



[[461 141]
 [176 540]]
             precision    recall  f1-score   support

         -1       0.72      0.77      0.74       602
          1       0.79      0.75      0.77       716

avg / total       0.76      0.76      0.76      1318

0.7594840667678301


In [98]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform', activation='sigmoid', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.2))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
 

[[439 163]
 [158 558]]
             precision    recall  f1-score   support

         -1       0.74      0.73      0.73       602
          1       0.77      0.78      0.78       716

avg / total       0.76      0.76      0.76      1318



In [99]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform', activation='sigmoid', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.5))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
print(classification_report(y_dailytest, pre_daily)) 
 

[[441 161]
 [158 558]]
             precision    recall  f1-score   support

         -1       0.74      0.73      0.73       602
          1       0.78      0.78      0.78       716

avg / total       0.76      0.76      0.76      1318

             precision    recall  f1-score   support

         -1       0.74      0.73      0.73       602
          1       0.78      0.78      0.78       716

avg / total       0.76      0.76      0.76      1318



In [105]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(30, input_dim=X_dailytrain.shape[1], kernel_initializer='uniform', activation='tanh', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.2))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_dailytrain, y_dailytrain)
pre_daily=model.predict(X_dailytest)
print(confusion_matrix(y_dailytest, pre_daily))  
print(classification_report(y_dailytest, pre_daily)) 
print (accuracy_score(y_dailytest, pre_daily))

[[456 146]
 [174 542]]
             precision    recall  f1-score   support

         -1       0.72      0.76      0.74       602
          1       0.79      0.76      0.77       716

avg / total       0.76      0.76      0.76      1318

0.7572078907435509


# LSTM miunte data with feature importance

In [14]:
data_feature=data.drop(['time','high','low','volume','MA_3','Momentum_3','RSI_3','MFI_3','Donchian_3'],axis = 1)
features_importance=data_feature.iloc[:,2:-1]

labels_importance=data_feature.iloc[:,-1]
min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(features_importance)
featuresimport_normalized = pd.DataFrame(np_scaled)

X_impor, X_impor_test, y_impor, y_impor_test = train_test_split(featuresimport_normalized, labels_importance, test_size = 0.20)  

In [49]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_impor.shape[1], kernel_initializer='uniform'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=10, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_impor, y_impor)
pre=model.predict(X_impor_test)
print(confusion_matrix(y_impor_test, pre))  
print(classification_report(y_impor_test, pre)) 
print (accuracy_score(y_impor_test, pre))

[[3062  792]
 [ 438 3933]]
             precision    recall  f1-score   support

         -1       0.87      0.79      0.83      3854
          1       0.83      0.90      0.86      4371

avg / total       0.85      0.85      0.85      8225

0.8504559270516717


In [51]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_impor.shape[1], kernel_initializer='uniform'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=50, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_impor, y_impor)
pre=model.predict(X_impor_test)
print(confusion_matrix(y_impor_test, pre))  
print(classification_report(y_impor_test, pre)) 
print (accuracy_score(y_impor_test, pre))

[[3842   12]
 [ 225 4146]]
             precision    recall  f1-score   support

         -1       0.94      1.00      0.97      3854
          1       1.00      0.95      0.97      4371

avg / total       0.97      0.97      0.97      8225

0.9711854103343465


In [52]:
from keras.constraints import maxnorm
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=X_impor.shape[1], kernel_initializer='uniform'))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_impor, y_impor)
pre=model.predict(X_impor_test)
print(confusion_matrix(y_impor_test, pre))  
print(classification_report(y_impor_test, pre)) 
print (accuracy_score(y_impor_test, pre))

[[3712  142]
 [   4 4367]]
             precision    recall  f1-score   support

         -1       1.00      0.96      0.98      3854
          1       0.97      1.00      0.98      4371

avg / total       0.98      0.98      0.98      8225

0.9822492401215805


In [15]:
from keras.constraints import maxnorm
def create_model(neurons=1):
	# create model
	model = Sequential()
	model.add(Dense(neurons, input_dim=X_impor.shape[1], kernel_initializer='uniform', activation='linear', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.2))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(X_impor, y_impor)
pre=model.predict(X_impor_test)
print(confusion_matrix(y_impor_test, pre))  
print(classification_report(y_impor_test, pre)) 
print (accuracy_score(y_impor_test, pre))

[[3841   33]
 [  39 4312]]
             precision    recall  f1-score   support

         -1       0.99      0.99      0.99      3874
          1       0.99      0.99      0.99      4351

avg / total       0.99      0.99      0.99      8225

0.9912462006079027


# LSTM for daily with features

In [16]:
daily_data=pd.read_csv('/Users/dingding/Desktop/GIIIUS_daily_new.csv')
null_columns=daily_data.columns[daily_data.isnull().any()]
daily_data[null_columns].isnull().sum()
daily_data=daily_data.dropna(subset = ['Donchian_3'])
daily_data_impor=daily_data.drop(['field','close','low','open','volume','CUR_MKT_CAP','PE_RATIO','RETURN_COM_EQY','EBITDA','IS_EPS','PROF_MARGIN','ROC_3','Return_3',
                                 'RSI_3','MFI_3','OBV_3','STD_3','Donchian_3','cap/ebitda','close/ebitda','cap/EPS','close/EPS',
                                'close/pro','return/ebitda','return/EPS','return/pro','return/ROE'],axis = 1)
daily_features_impor=daily_data_impor.iloc[:,0:-1]
daily_labels_impor=daily_data_impor.iloc[:,-1]
min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(daily_features_impor)
daily_featuresimport_normalized = pd.DataFrame(np_scaled)



In [18]:
Xdaily_impor, Xdaily_impor_test, ydaily_impor, ydaily_impor_test = train_test_split(daily_featuresimport_normalized, daily_labels_impor, test_size = 0.20)  

In [19]:
from keras.constraints import maxnorm
def create_model(neurons=30):
	# create model
	model = Sequential()
	model.add(Dense(neurons, input_dim=Xdaily_impor.shape[1], kernel_initializer='uniform', activation='tanh', kernel_constraint=maxnorm(4)))
	model.add(Dropout(0.2))
	model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
model.fit(Xdaily_impor, ydaily_impor)
pre=model.predict(Xdaily_impor_test)
print(confusion_matrix(ydaily_impor_test, pre))  
print(classification_report(ydaily_impor_test, pre)) 
print (accuracy_score(ydaily_impor_test, pre))


[[440 186]
 [141 551]]
             precision    recall  f1-score   support

         -1       0.76      0.70      0.73       626
          1       0.75      0.80      0.77       692

avg / total       0.75      0.75      0.75      1318

0.7518968133535661
