In [1]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.svm import SVC
import math as m
from pandas import Series, DataFrame, Panel
from datetime import datetime, date, time
import pandas as pd
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, BaggingClassifier
from collections import Counter
from sklearn.metrics import roc_auc_score, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.grid_search import GridSearchCV

import xgboost as xgb

import lightgbm as lgb

from catboost import CatBoostClassifier

from sklearn import svm

from fastFM import als
from sklearn.model_selection import train_test_split

def warn(*args, **kwargs): pass
import warnings
warnings.warn = warn

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, log_loss
from sklearn import decomposition

from sklearn.preprocessing import LabelEncoder
from sklearn.cross_validation import StratifiedShuffleSplit

/Users/dingding/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/dingding/anaconda/lib/python3.5/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [2]:
data=pd.read_csv('/Users/dingding/Desktop/GIII_3minutenew.csv')
data=data.drop(data.index[[0,1,2,3]])


In [3]:
null_columns=data.columns[data.isnull().any()]
data[null_columns].isnull().sum()

MFI_3         399
Donchian_3      1
dtype: int64

In [4]:
data=data.dropna(subset = ['MFI_3', 'Donchian_3'])

In [5]:
features=data.iloc[:,2:-2]
features
labels=data.iloc[:,-1]

In [6]:
import pandas as pd
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(features)
features_normalized = pd.DataFrame(np_scaled)

#  SVM Kernal without scailing

In [7]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(features_normalized, labels, test_size = 0.20)  


In [18]:
clf = svm.SVC()
clf.fit(X_train, y_train)  
y_pred = clf.predict(X_test)  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 
print (accuracy_score(y_test, y_pred))

[[3122  712]
 [ 782 3609]]
             precision    recall  f1-score   support

         -1       0.80      0.81      0.81      3834
          1       0.84      0.82      0.83      4391

avg / total       0.82      0.82      0.82      8225

0.8183586626139817


# SVM Linear C=1, 10,100,100

In [109]:
from sklearn.svm import SVC  
svclassifier = SVC(C=1,kernel='linear')  
svclassifier.fit(X_train, y_train)  

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [110]:
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 
print (accuracy_score(y_test, y_pred))

[[3092  708]
 [ 795 3630]]
             precision    recall  f1-score   support

         -1       0.80      0.81      0.80      3800
          1       0.84      0.82      0.83      4425

avg / total       0.82      0.82      0.82      8225

0.8172644376899696


In [111]:
svclassifier = SVC(C=10,kernel='linear')  
svclassifier.fit(X_train, y_train)  

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [112]:
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print (accuracy_score(y_test, y_pred))

[[3160  640]
 [ 653 3772]]
             precision    recall  f1-score   support

         -1       0.83      0.83      0.83      3800
          1       0.85      0.85      0.85      4425

avg / total       0.84      0.84      0.84      8225

0.8427963525835866


In [113]:
svclassifier = SVC(C=100,kernel='linear')  
svclassifier.fit(X_train, y_train)  

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [114]:
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 
print (accuracy_score(y_test, y_pred))

[[3203  597]
 [ 532 3893]]
             precision    recall  f1-score   support

         -1       0.86      0.84      0.85      3800
          1       0.87      0.88      0.87      4425

avg / total       0.86      0.86      0.86      8225

0.8627355623100303


# SVM poly

In [115]:
from sklearn.svm import SVC  
svclassifier = SVC(C=1,kernel='poly', degree=8)  
svclassifier.fit(X_train, y_train)  

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [116]:
y_pred = svclassifier.predict(X_test)  

In [117]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  
print (accuracy_score(y_test, y_pred))

[[   0 3800]
 [   0 4425]]
             precision    recall  f1-score   support

         -1       0.00      0.00      0.00      3800
          1       0.54      1.00      0.70      4425

avg / total       0.29      0.54      0.38      8225

0.5379939209726444


In [118]:
svclassifier = SVC(C=10,kernel='poly', degree=8)  
svclassifier.fit(X_train, y_train)  

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [119]:
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  
print (accuracy_score(y_test, y_pred))

[[ 411 3389]
 [ 103 4322]]
             precision    recall  f1-score   support

         -1       0.80      0.11      0.19      3800
          1       0.56      0.98      0.71      4425

avg / total       0.67      0.58      0.47      8225

0.5754407294832826


In [120]:
svclassifier = SVC(C=100,kernel='poly', degree=8)  
svclassifier.fit(X_train, y_train)  

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [121]:
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  
print (accuracy_score(y_test, y_pred))

[[3610  190]
 [2394 2031]]
             precision    recall  f1-score   support

         -1       0.60      0.95      0.74      3800
          1       0.91      0.46      0.61      4425

avg / total       0.77      0.69      0.67      8225

0.6858358662613981


# SVM rbf, C=1,10,100,100

In [122]:
svclassifier = SVC(C=1,kernel='rbf')  
svclassifier.fit(X_train, y_train)  
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  
print (accuracy_score(y_test, y_pred))

[[3042  758]
 [ 850 3575]]
             precision    recall  f1-score   support

         -1       0.78      0.80      0.79      3800
          1       0.83      0.81      0.82      4425

avg / total       0.80      0.80      0.80      8225

0.8044984802431611


In [123]:
svclassifier = SVC(C=10,kernel='rbf')  
svclassifier.fit(X_train, y_train)  
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 
print (accuracy_score(y_test, y_pred))

[[3037  763]
 [ 709 3716]]
             precision    recall  f1-score   support

         -1       0.81      0.80      0.80      3800
          1       0.83      0.84      0.83      4425

avg / total       0.82      0.82      0.82      8225

0.821033434650456


In [124]:
svclassifier = SVC(C=100,kernel='rbf')  
svclassifier.fit(X_train, y_train)  
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 
print (accuracy_score(y_test, y_pred))

[[3141  659]
 [ 625 3800]]
             precision    recall  f1-score   support

         -1       0.83      0.83      0.83      3800
          1       0.85      0.86      0.86      4425

avg / total       0.84      0.84      0.84      8225

0.8438905775075988


# SVM sigmod C=1,10,100,1000

In [125]:
svclassifier = SVC(C=1,kernel='sigmoid')  
svclassifier.fit(X_train, y_train)  
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 
print (accuracy_score(y_test, y_pred))

[[3055  745]
 [ 872 3553]]
             precision    recall  f1-score   support

         -1       0.78      0.80      0.79      3800
          1       0.83      0.80      0.81      4425

avg / total       0.80      0.80      0.80      8225

0.8034042553191489


In [126]:
svclassifier = SVC(C=10,kernel='sigmoid')  
svclassifier.fit(X_train, y_train)  
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  
print (accuracy_score(y_test, y_pred))

[[2753 1047]
 [1105 3320]]
             precision    recall  f1-score   support

         -1       0.71      0.72      0.72      3800
          1       0.76      0.75      0.76      4425

avg / total       0.74      0.74      0.74      8225

0.7383586626139818


In [127]:
svclassifier = SVC(C=100,kernel='sigmoid')  
svclassifier.fit(X_train, y_train)  
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  
print (accuracy_score(y_test, y_pred))

[[2694 1106]
 [1188 3237]]
             precision    recall  f1-score   support

         -1       0.69      0.71      0.70      3800
          1       0.75      0.73      0.74      4425

avg / total       0.72      0.72      0.72      8225

0.7210942249240122


In [33]:
k=['rbf', 'linear','poly','sigmoid']
c= [1,10,100]
g=[1,0.1,0.001]
param_grid=dict(kernel=k, C=c, gamma=g)
print(param_grid)
svr=svm.SVC()
grid = GridSearchCV(svr, param_grid, cv=5,scoring='accuracy')

{'gamma': [1, 0.1, 0.001], 'C': [1, 10, 100], 'kernel': ['rbf', 'linear', 'poly', 'sigmoid']}


In [34]:
grid.fit(X_train, y_train)  
print()
print("Grid scores on development set:")
print()  
print(grid.grid_scores_ ) 
print("Best parameters set found on development set:")
print()
print(grid.best_params_)
print("Grid best score:")
print()
print (grid.best_score_)


Grid scores on development set:

[mean: 0.82010, std: 0.00608, params: {'gamma': 1, 'kernel': 'rbf', 'C': 1}, mean: 0.82262, std: 0.00711, params: {'gamma': 1, 'kernel': 'linear', 'C': 1}, mean: 0.84563, std: 0.00518, params: {'gamma': 1, 'kernel': 'poly', 'C': 1}, mean: 0.43039, std: 0.00595, params: {'gamma': 1, 'kernel': 'sigmoid', 'C': 1}, mean: 0.81311, std: 0.00596, params: {'gamma': 0.1, 'kernel': 'rbf', 'C': 1}, mean: 0.82262, std: 0.00711, params: {'gamma': 0.1, 'kernel': 'linear', 'C': 1}, mean: 0.80779, std: 0.00584, params: {'gamma': 0.1, 'kernel': 'poly', 'C': 1}, mean: 0.79487, std: 0.00603, params: {'gamma': 0.1, 'kernel': 'sigmoid', 'C': 1}, mean: 0.80879, std: 0.00681, params: {'gamma': 0.001, 'kernel': 'rbf', 'C': 1}, mean: 0.82262, std: 0.00711, params: {'gamma': 0.001, 'kernel': 'linear', 'C': 1}, mean: 0.53320, std: 0.00003, params: {'gamma': 0.001, 'kernel': 'poly', 'C': 1}, mean: 0.80824, std: 0.00715, params: {'gamma': 0.001, 'kernel': 'sigmoid', 'C': 1}, mean:

# SVM_daliy_price

In [20]:
daily_data=pd.read_csv('/Users/dingding/Desktop/GIIIUS_daily_new.csv')
null_columns=daily_data.columns[daily_data.isnull().any()]
daily_data[null_columns].isnull().sum()
daily_data=daily_data.dropna(subset = ['Donchian_3'])
daily_data=daily_data.drop(['field','RETURN_COM_EQY','EBITDA','IS_EPS','PROF_MARGIN','ROC_3','Return_3'],axis = 1)

In [21]:
daily_features=daily_data.iloc[:,0:-1]
daily_labels=daily_data.iloc[:,-1]

In [22]:
min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(daily_features)
dailyfeatures_normalized = pd.DataFrame(np_scaled)

In [23]:
X_dailytrain, X_dailytest, y_dailytrain, y_dailytest = train_test_split(dailyfeatures_normalized, daily_labels, test_size = 0.20)  

In [24]:
clf = svm.SVC()
clf.fit(X_dailytrain, y_dailytrain)  
y_dailypred = clf.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[444 155]
 [152 567]]
             precision    recall  f1-score   support

         -1       0.74      0.74      0.74       599
          1       0.79      0.79      0.79       719

avg / total       0.77      0.77      0.77      1318

0.7670713201820941


In [132]:
svclassifier = SVC(C=1,kernel='linear')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[477 151]
 [147 543]]
             precision    recall  f1-score   support

         -1       0.76      0.76      0.76       628
          1       0.78      0.79      0.78       690

avg / total       0.77      0.77      0.77      1318

0.7738998482549317


In [133]:
svclassifier = SVC(C=10,kernel='linear')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[487 141]
 [134 556]]
             precision    recall  f1-score   support

         -1       0.78      0.78      0.78       628
          1       0.80      0.81      0.80       690

avg / total       0.79      0.79      0.79      1318

0.791350531107739


In [134]:
svclassifier = SVC(C=100,kernel='linear')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[490 138]
 [125 565]]
             precision    recall  f1-score   support

         -1       0.80      0.78      0.79       628
          1       0.80      0.82      0.81       690

avg / total       0.80      0.80      0.80      1318

0.8004552352048558


In [135]:
svclassifier = SVC(C=1,kernel='poly')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[488 140]
 [166 524]]
             precision    recall  f1-score   support

         -1       0.75      0.78      0.76       628
          1       0.79      0.76      0.77       690

avg / total       0.77      0.77      0.77      1318

0.7678300455235205


In [136]:
svclassifier = SVC(C=10,kernel='poly')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[481 147]
 [156 534]]
             precision    recall  f1-score   support

         -1       0.76      0.77      0.76       628
          1       0.78      0.77      0.78       690

avg / total       0.77      0.77      0.77      1318

0.7701062215477997


In [137]:
svclassifier = SVC(C=100,kernel='poly')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[474 154]
 [139 551]]
             precision    recall  f1-score   support

         -1       0.77      0.75      0.76       628
          1       0.78      0.80      0.79       690

avg / total       0.78      0.78      0.78      1318

0.7776934749620638


In [138]:
svclassifier = SVC(C=1,kernel='rbf')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[477 151]
 [148 542]]
             precision    recall  f1-score   support

         -1       0.76      0.76      0.76       628
          1       0.78      0.79      0.78       690

avg / total       0.77      0.77      0.77      1318

0.7731411229135053


In [139]:
svclassifier = SVC(C=10,kernel='rbf')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[475 153]
 [142 548]]
             precision    recall  f1-score   support

         -1       0.77      0.76      0.76       628
          1       0.78      0.79      0.79       690

avg / total       0.78      0.78      0.78      1318

0.776176024279211


In [140]:
svclassifier = SVC(C=100,kernel='rbf')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[465 163]
 [116 574]]
             precision    recall  f1-score   support

         -1       0.80      0.74      0.77       628
          1       0.78      0.83      0.80       690

avg / total       0.79      0.79      0.79      1318

0.7883156297420334


In [144]:
svclassifier = SVC(C=1,kernel='sigmoid')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[476 152]
 [147 543]]
             precision    recall  f1-score   support

         -1       0.76      0.76      0.76       628
          1       0.78      0.79      0.78       690

avg / total       0.77      0.77      0.77      1318

0.7731411229135053


In [145]:
svclassifier = SVC(C=10,kernel='sigmoid')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[471 157]
 [151 539]]
             precision    recall  f1-score   support

         -1       0.76      0.75      0.75       628
          1       0.77      0.78      0.78       690

avg / total       0.77      0.77      0.77      1318

0.7663125948406677


In [146]:
svclassifier = SVC(C=100,kernel='sigmoid')  
svclassifier.fit(X_dailytrain, y_dailytrain)  
y_dailypred = svclassifier.predict(X_dailytest)  
print(confusion_matrix(y_dailytest,y_dailypred))  
print(classification_report(y_dailytest,y_dailypred)) 
print (accuracy_score(y_dailytest, y_dailypred))

[[407 221]
 [220 470]]
             precision    recall  f1-score   support

         -1       0.65      0.65      0.65       628
          1       0.68      0.68      0.68       690

avg / total       0.67      0.67      0.67      1318

0.665402124430956


In [156]:
grid.fit(X_dailytrain, y_dailytrain)  
print('')
print("Grid scores on development set:")
print('')  
print(grid.grid_scores_ ) 
print("Best parameters set found on development set:")
print('')
print(grid.best_params_)
print("Grid best score:")
print('')
print (grid.best_score_)


Grid scores on development set:

[mean: 0.76846, std: 0.01522, params: {'C': 1, 'kernel': 'rbf', 'gamma': 1}, mean: 0.76846, std: 0.01324, params: {'C': 1, 'kernel': 'linear', 'gamma': 1}, mean: 0.80262, std: 0.00910, params: {'C': 1, 'kernel': 'poly', 'gamma': 1}, mean: 0.54128, std: 0.00004, params: {'C': 1, 'kernel': 'sigmoid', 'gamma': 1}, mean: 0.76618, std: 0.01347, params: {'C': 1, 'kernel': 'rbf', 'gamma': 0.1}, mean: 0.76846, std: 0.01324, params: {'C': 1, 'kernel': 'linear', 'gamma': 0.1}, mean: 0.76618, std: 0.01529, params: {'C': 1, 'kernel': 'poly', 'gamma': 0.1}, mean: 0.75232, std: 0.00973, params: {'C': 1, 'kernel': 'sigmoid', 'gamma': 0.1}, mean: 0.76504, std: 0.01519, params: {'C': 1, 'kernel': 'rbf', 'gamma': 0.001}, mean: 0.76846, std: 0.01324, params: {'C': 1, 'kernel': 'linear', 'gamma': 0.001}, mean: 0.54128, std: 0.00004, params: {'C': 1, 'kernel': 'poly', 'gamma': 0.001}, mean: 0.61833, std: 0.00814, params: {'C': 1, 'kernel': 'sigmoid', 'gamma': 0.001}, mean:

# SVM for minute data with feature importances

In [25]:
data_feature=data.drop(['time','close','high','low','open','volume','MA_3','Force_3'],axis = 1)

In [26]:
features_importance=data_feature.iloc[:,2:-2]

labels_importance=data_feature.iloc[:,-1]

In [27]:
min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(features_importance)
featuresimport_normalized = pd.DataFrame(np_scaled)


In [28]:
X_impor, X_impor_test, y_impor, y_impor_test = train_test_split(featuresimport_normalized, labels_importance, test_size = 0.20)  

In [29]:
clf = svm.SVC()
clf.fit(X_impor, y_impor)  
y_dailypred = clf.predict(X_impor_test)  
print(confusion_matrix(y_impor_test,y_dailypred))  
print(classification_report(y_impor_test,y_dailypred)) 
print (accuracy_score(y_impor_test, y_dailypred))

[[3034  833]
 [ 734 3624]]
             precision    recall  f1-score   support

         -1       0.81      0.78      0.79      3867
          1       0.81      0.83      0.82      4358

avg / total       0.81      0.81      0.81      8225

0.809483282674772


In [12]:
k=['rbf', 'linear','poly','sigmoid']
c= [1,10,100]
g=[1,0.1,0.001]
param_grid=dict(kernel=k, C=c, gamma=g)
print(param_grid)
svr=svm.SVC()
grid = GridSearchCV(svr, param_grid, cv=5,scoring='accuracy')

{'gamma': [1, 0.1, 0.001], 'C': [1, 10, 100], 'kernel': ['rbf', 'linear', 'poly', 'sigmoid']}


In [13]:
grid.fit(X_impor, y_impor)  
print('')
print("Grid scores on development set:")
print('')  
print(grid.grid_scores_ ) 
print("Best parameters set found on development set:")
print('')
print(grid.best_params_)
print("Grid best score:")
print('')
print (grid.best_score_)


Grid scores on development set:

[mean: 0.81490, std: 0.00370, params: {'gamma': 1, 'kernel': 'rbf', 'C': 1}, mean: 0.81162, std: 0.00428, params: {'gamma': 1, 'kernel': 'linear', 'C': 1}, mean: 0.81542, std: 0.00409, params: {'gamma': 1, 'kernel': 'poly', 'C': 1}, mean: 0.53931, std: 0.00244, params: {'gamma': 1, 'kernel': 'sigmoid', 'C': 1}, mean: 0.81116, std: 0.00507, params: {'gamma': 0.1, 'kernel': 'rbf', 'C': 1}, mean: 0.81162, std: 0.00428, params: {'gamma': 0.1, 'kernel': 'linear', 'C': 1}, mean: 0.80387, std: 0.00480, params: {'gamma': 0.1, 'kernel': 'poly', 'C': 1}, mean: 0.81055, std: 0.00416, params: {'gamma': 0.1, 'kernel': 'sigmoid', 'C': 1}, mean: 0.80986, std: 0.00321, params: {'gamma': 0.001, 'kernel': 'rbf', 'C': 1}, mean: 0.81162, std: 0.00428, params: {'gamma': 0.001, 'kernel': 'linear', 'C': 1}, mean: 0.53359, std: 0.00001, params: {'gamma': 0.001, 'kernel': 'poly', 'C': 1}, mean: 0.81007, std: 0.00344, params: {'gamma': 0.001, 'kernel': 'sigmoid', 'C': 1}, mean:

# SVM for daily data with feature importances

In [30]:
daily_data=pd.read_csv('/Users/dingding/Desktop/GIIIUS_daily_new.csv')
null_columns=daily_data.columns[daily_data.isnull().any()]
daily_data[null_columns].isnull().sum()
daily_data=daily_data.dropna(subset = ['Donchian_3'])
daily_data_impor=daily_data.drop(['field','high','close','low','open','volume','CUR_MKT_CAP','PE_RATIO','RETURN_COM_EQY','EBITDA','IS_EPS','PROF_MARGIN','ROC_3','Return_3',
                                  'cap/ebitda','close/ebitda','cap/EPS','close/EPS','cap/ROE',
                                  'close/ROE','cap/pro','close/pro','return/ebitda','return/EPS','return/pro','return/ROE'],axis = 1)
daily_features_impor=daily_data_impor.iloc[:,0:-1]
daily_labels_impor=daily_data_impor.iloc[:,-1]
min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(daily_features_impor)
daily_featuresimport_normalized = pd.DataFrame(np_scaled)



In [31]:
X_dailyimpor, X_dailyimpor_test, y_dailyimpor, y_dailyimpor_test = train_test_split(daily_featuresimport_normalized, daily_labels_impor, test_size = 0.20)  

In [16]:
k=['rbf', 'linear','poly','sigmoid']
c= [1,10,100]
g=[1,0.1,0.001]
param_grid=dict(kernel=k, C=c, gamma=g)
print(param_grid)
svr=svm.SVC()
grid = GridSearchCV(svr, param_grid, cv=5,scoring='accuracy')

{'gamma': [1, 0.1, 0.001], 'C': [1, 10, 100], 'kernel': ['rbf', 'linear', 'poly', 'sigmoid']}


In [17]:
grid.fit(X_dailyimpor, y_dailyimpor)  
print('')
print("Grid scores on development set:")
print('')  
print(grid.grid_scores_ ) 
print("Best parameters set found on development set:")
print('')
print(grid.best_params_)
print("Grid best score:")
print('')
print (grid.best_score_)


Grid scores on development set:

[mean: 0.76846, std: 0.00848, params: {'gamma': 1, 'kernel': 'rbf', 'C': 1}, mean: 0.76941, std: 0.00833, params: {'gamma': 1, 'kernel': 'linear', 'C': 1}, mean: 0.77434, std: 0.00940, params: {'gamma': 1, 'kernel': 'poly', 'C': 1}, mean: 0.47998, std: 0.01701, params: {'gamma': 1, 'kernel': 'sigmoid', 'C': 1}, mean: 0.76884, std: 0.00674, params: {'gamma': 0.1, 'kernel': 'rbf', 'C': 1}, mean: 0.76941, std: 0.00833, params: {'gamma': 0.1, 'kernel': 'linear', 'C': 1}, mean: 0.75195, std: 0.00803, params: {'gamma': 0.1, 'kernel': 'poly', 'C': 1}, mean: 0.76637, std: 0.00762, params: {'gamma': 0.1, 'kernel': 'sigmoid', 'C': 1}, mean: 0.76561, std: 0.01091, params: {'gamma': 0.001, 'kernel': 'rbf', 'C': 1}, mean: 0.76941, std: 0.00833, params: {'gamma': 0.001, 'kernel': 'linear', 'C': 1}, mean: 0.53521, std: 0.00020, params: {'gamma': 0.001, 'kernel': 'poly', 'C': 1}, mean: 0.63504, std: 0.00729, params: {'gamma': 0.001, 'kernel': 'sigmoid', 'C': 1}, mean:

In [32]:
clf = svm.SVC()
clf.fit(X_dailyimpor, y_dailyimpor)  
y_dailypred = clf.predict(X_dailyimpor_test)  
print(confusion_matrix(y_dailyimpor_test,y_dailypred))  
print(classification_report(y_dailyimpor_test,y_dailypred)) 
print (accuracy_score(y_dailyimpor_test, y_dailypred))

[[453 174]
 [137 554]]
             precision    recall  f1-score   support

         -1       0.77      0.72      0.74       627
          1       0.76      0.80      0.78       691

avg / total       0.76      0.76      0.76      1318

0.7640364188163885
